// Wire `skein hook` into each agent's session-start surface.
//
// M0.5 (PRD §7, Q1) resolved the gating unknown: all three agents have one,
// and two of them share a schema.
//
//   claude    ~/.claude/settings.json     hooks.SessionStart[]
//   codex     ~/.codex/hooks.json         hooks.SessionStart[]   (same shape)
//   opencode  ~/.config/opencode/plugins/skein.js
//                                         experimental.chat.system.transform
//
// Idempotent, additive, and it backs up anything it touches. Users have their
// own hooks in these files; appending is the only acceptable behaviour.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { HOME, XDG_CONFIG, XDG_DATA } from './paths.js'

const MARKER = 'skein hook'

const TARGETS = {
  claude: join(HOME, '.claude', 'settings.json'),
  codex: join(HOME, '.codex', 'hooks.json'),
}
const OPENCODE_PLUGIN = join(XDG_CONFIG, 'opencode', 'plugins', 'skein.js')

const readJson = f => {
  try { return JSON.parse(readFileSync(f, 'utf8')) } catch { return {} }
}

const backup = f => {
  if (!existsSync(f)) return
  try { copyFileSync(f, `${f}.skein-bak`) } catch {}
}

function installHookJson(file) {
  const cfg = readJson(file)
  cfg.hooks ??= {}
  cfg.hooks.SessionStart ??= []
  const already = JSON.stringify(cfg.hooks.SessionStart).includes(MARKER)
  if (already) return 'already wired'
  cfg.hooks.SessionStart.push({
    matcher: '',
    hooks: [{ type: 'command', command: MARKER, timeout: 10 }],
  })
  backup(file)
  mkdirSync(dirname(file), { recursive: true })
  writeFileSync(file, `${JSON.stringify(cfg, null, 2)}\n`)
  return 'wired'
}

const PLUGIN = `// skein — ambient coordination context for opencode.
// Generated by \`skein install\`. Safe to delete; run install again to restore.
import { execFile } from "node:child_process"

export const SkeinAmbientContext = async ({ directory }) => ({
  "experimental.chat.system.transform": async (input, output) => {
    const line = await new Promise(resolve => {
      execFile("skein", ["hook"], { cwd: directory, timeout: 10_000 },
        (err, stdout) => resolve(err ? "" : (stdout || "").trim()))
    })
    if (line) output.system.push(line)
  },
})
`

function installOpencodePlugin() {
  if (existsSync(OPENCODE_PLUGIN) && readFileSync(OPENCODE_PLUGIN, 'utf8').includes('skein')) return 'already wired'
  mkdirSync(dirname(OPENCODE_PLUGIN), { recursive: true })
  backup(OPENCODE_PLUGIN)
  writeFileSync(OPENCODE_PLUGIN, PLUGIN)
  return 'wired'
}

export function install(args = []) {
  const only = args.filter(a => !a.startsWith('-'))
  const want = a => !only.length || only.includes(a)
  const lines = []

  for (const [agent, file] of Object.entries(TARGETS)) {
    if (!want(agent)) continue
    if (!existsSync(dirname(file))) { lines.push(`  ${agent.padEnd(9)} not installed — skipped`); continue }
    try { lines.push(`  ${agent.padEnd(9)} ${installHookJson(file)}  ${file.replace(HOME, '~')}`) }
    catch (e) { lines.push(`  ${agent.padEnd(9)} failed: ${e.message}`) }
  }
  if (want('opencode')) {
    if (!existsSync(join(XDG_CONFIG, 'opencode')) && !existsSync(join(XDG_DATA, 'opencode'))) {
      lines.push(`  opencode  not installed — skipped`)
    } else {
      try { lines.push(`  opencode  ${installOpencodePlugin()}  ${OPENCODE_PLUGIN.replace(HOME, '~')}`) }
      catch (e) { lines.push(`  opencode  failed: ${e.message}`) }
    }
  }

  return {
    code: 0,
    text: `skein install\n\n${lines.join('\n')}\n\nStart a new session to pick it up. Backups are alongside each file as *.skein-bak.\nskein only ever reads your agents' files; these are its own config entries.`,
  }
}
